Proc import datafile='C:\Users\haesong\Desktop\hsongchoi\Table7\all.csv' 
Out=all_data dbms=csv replace;
run;
Proc import datafile='C:\Users\haesong\Desktop\hsongchoi\Table7\rate.csv' 
Out=int dbms=csv replace;
run;
proc rank data=int out=int descending group=4;
var rate;
ranks r_rate;
run;
data int;
set int;
if r_rate=3 then rrate=1;
if r_rate=0 then rrate=0;
if r_rate=1 then rrate=0;
if r_rate=2 then rrate=0;
run;

proc sort data=int out=int;
by date;
run;
proc sort data=all_data out=all_data;
by date;
run;
data all_data1;
merge all_data int;
by date;
run;
data all_data1;
set all_data1;
if date=. then delete;
run;

data reg;
set all_data1;
owner1=log(owner);
if owner=0 then owner1=0;
p_owner1=log(p_owner);
if p_owner=0 then p_owner1=0;
dyrate=dy*rate;
owner1rate=owner1*rate;
dyrrate=dy*rrate;
owner1rrate=owner1*rate;
owner2=owner*0.000001;
p_owner2=p_owner*0.0000001;
owner2rate=owner2*rate;

run;
proc sort data=reg;
by code;
run;
proc means data=reg mean;
var dy;
class code;
output out=divmean mean=div_mean; /* mean   */
run; 
proc sort data=divmean;
by descending div_mean;
run;
data divmean;
set divmean;
if div_mean>0;
run;
proc rank data=divmean out=divrank descending group=4;
var div_mean;
ranks r_div;
run;
data divrank;
set divrank;
if r_div=0 then high=1;
if r_div=1 then high=0;
if r_div=2 then high=0;
if r_div=3 then high=0;
drop _TYPE_ _FREQ_;
run;
data high;
set divrank;
if high=1 then output high;
run;
proc sort data=high;
by code;
run;
data ex;
merge high reg;
by code;
if high=. then delete;
run;
proc sort data=reg;
by code;
run;
proc sort data=divrank;
by code;
run;
data reg1;
merge divrank reg;
by code;
run;
data reg1;
set reg1;
if date=. then delete;
run;
data reg1;
set reg1;
highrate=high*rate;
highowner1=owner1*high;
highdyrate=high*dyrate;
highdy=high*dy;
highowner1rate=high*owner1rate;
if div_mean=. then delete;

run;


proc reg data=reg1;
model return=owner1rrate dyrrate p_return p_owner1 /vif;
run;
proc panel data=reg1;
model return=p_return highrate highowner1 p_owner1/fixonetime;
id code date;
run;
proc panel data=reg1;
model return=p_return dyrate highowner1 highdyrate highowner1rate p_owner1/fixonetime;
id code date;
run;
proc panel data=reg1;
model return=highrate highowner1 dy owner1 p_owner1 p_return/fixonetime;
id code date;
run;
